# R2R Configuration
app:
  name: "OCR-RAG-R2R"
  version: "1.0.0"

database:
  provider: "postgres"
  connection_string: "${R2R_DATABASE_URL}"

embedding:
  provider: "sentence-transformers"
  model: "all-MiniLM-L6-v2"
  dimension: 384

vector_database:
  provider: "pgvector"
  collection_name: "ocr_documents"

ingestion:
  chunk_size: 512
  chunk_overlap: 50

retrieval:
  search_limit: 10
  similarity_threshold: 0.7

logging:
  level: "INFO"
  format: "json"