app:
  name: "OCR-RAG-R2R"
  version: "1.0.0"

database:
  provider: "postgres"
  connection_string: "postgresql://postgres:postgres@postgres:5432/r2r"

embedding:
  provider: "local"
  model: "sentence-transformers/all-MiniLM-L6-v2"
  dimension: 384

vector_database:
  provider: "pgvector"
  collection_name: "ocr_documents"

ingestion:
  chunk_size: 512
  chunk_overlap: 50

retrieval:
  search_limit: 10
  similarity_threshold: 0.7
  search_type: "hybrid"

llm:
  provider: "openai"
  model: "gpt-3.5-turbo"

logging:
  level: "INFO"